apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: ex-multi-2rj-20-nonspot
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
spec:
  failurePolicy:
    maxRestarts: 2
  replicatedJobs:
    - name: rs-aaa
      replicas: 1
      template:
        spec:
          parallelism: 4 # num node per node pool
          completions: 4
          backoffLimit: 0
          template:
            spec:
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                cloud.google.com/gke-tpu-topology: 4x4
              containers:
              - name: jax-tpu
                image: ubuntu
                ports:
                - containerPort: 8471
                - containerPort: 8080
                command:
                - bash
                - -c
                - |
                  sleep 1000
                resources:
                  limits:
                    google.com/tpu: 4
    - name: rs-bbb
      replicas: 1
      template:
        spec:
          parallelism: 1 # num node per node pool
          completions: 1
          backoffLimit: 0
          template:
            spec:
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                cloud.google.com/gke-tpu-topology: 2x2
              containers:
              - name: jax-tpu
                image: ubuntu
                ports:
                - containerPort: 8471
                - containerPort: 8080
                command:
                - bash
                - -c
                - |
                  sleep 1000
                resources:
                  limits:
                    google.com/tpu: 4
